-- Exemple d'insertion d'une peinture
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('Ma peinture', 'description: enitsu Dream State This listing is for a high quality print of one of my TikTok paintings and is a Demon Slayer fans dream, with a dream theme! This uses multiple spray paint art techniques and depicts Zenitsu in a dream state using his rolling thunder attack in the real world with his dream world shown in a cosmic dream catcher. Print options are as follows:A3 (297mm x 420mm) Digital prints - These are standard 4 colour digital prints and come in a gloss finish. A2 (420mm x 594mm) Giclee prints - These 12 colour prints ant the larger size are created on 230gsm Matt finish archival paper. They are the ultimate printing method for the best display of this type of art.  Finish the look with a frame! I use high quality timber and glass frames in black and I would highly recommend this! This piece features planets and a space scene as well as a stencil art of darth vader, a galactic fleet ship and clone troopers.  The lead time stated us an average. Due to forever changing numbers of commissions it could take a little bit longer. Please feel free to get in touch prior to purchase if you have any queries.', 'Paysage', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('balablaa', 'ceci est une Description de ma peinture...', 'Super Heros', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('Ma peinture2', 'ceci est une Description de ma peinture...', 'Fleur', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('Ma peinture3', 'ceci est une Description de ma peinture...', 'Paysage', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('Ma peinture6', 'ceci est une Description de ma peinture...', 'Paysage', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('Ma peinture9', 'ceci est une Description de ma peinture...', 'Paysage', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('Ma peinture11', 'ceci est une Description de ma peinture...', 'Paysage', '2024-06-24', 120.0, '40x60', 'available');
INSERT INTO paint (name, description, category, date_creation, price, dimensions, status) VALUES ('test', 'ceci est une Description de ma peinture...', 'cascade', '2024-06-24', 120.0, '40x60', 'available');

-- Supposons que l'id_paint retourné est 1
INSERT INTO paint_image (id_paint, url) VALUES (1, '/images/platforms/planete.jpg'), (1, '/images/platforms/cascade.jpg'),(1, '/images/platforms/cascade.jpg');
INSERT INTO paint_image (id_paint, url) VALUES (2, '/images/platforms/cascade.jpg');
INSERT INTO paint_image (id_paint, url) VALUES (3, '/images/platforms/heros.jpg');
INSERT INTO paint_image (id_paint, url) VALUES (4, '/images/platforms/fleur.jpg');
INSERT INTO paint_image (id_paint, url) VALUES (5, '/images/platforms/pochoir.jpg'); 
